version: "3"

networks:
  mongo_net:
    external: false

volumes:
  db_data:
    external: false

services:
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    networks:
      - "mongo_net"
    ports:
      - "27017:27017"
    volumes:
      - "db_data:/data/db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=password"

  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    restart: always
    networks:
      - "mongo_net"
    ports:
      - "8081:8081"
    depends_on:
      - "mongo"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=password"
      - "ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/"
